spring:
  config:
    activate:
      on-profile: "dev"
  application:
    name:clothing_store;
  datasource:
    url: jdbc:postgresql://localhost:5432/clothing_store_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML
server:
  port: 8080
