spring:
  application:
    name: clothing_store;
  datasource:
    url: jdbc:postgresql://localhost:5432/clothing_store_db_2
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
